### ISSUE TITLE
Data preparation script is missing

### ISSUE THREAD

**Issue by happyjin** [AmourWaltz/BayesLMs#1]
Thanks for this awesome project. I fail to run the script because the data preparation part is missing. Could you share the data preparation script to help me re-run the experiments?

**Comment by AmourWaltz** [comment]
The data preparation part you can refer to the Kaldi recipe under https://github.com/kaldi-asr/kaldi/blob/master/egs/swbd/s5c/steps/pytorchnn/ and https://github.com/kaldi-asr/kaldi/blob/master/egs/swbd/s5c/local/pytorchnn/ for more details
